export type AsmaName = {
  n: number;
  ar: string;
  translit: string;
  en: string;
  ku: string;
};

// 99 Names of Allah (Al-Asma Al-Husna)
export const ASMA_ALLAH: AsmaName[] = [
  { n: 1, ar: "الرَّحْمَٰنُ", translit: "Ar-Rahman", en: "The Most Compassionate", ku: "زۆر بەبەزەیی" },
  { n: 2, ar: "الرَّحِيمُ", translit: "Ar-Raheem", en: "The Most Merciful", ku: "میهرەبان" },
  { n: 3, ar: "الْمَلِكُ", translit: "Al-Malik", en: "The King", ku: "پاشا" },
  { n: 4, ar: "الْقُدُّوسُ", translit: "Al-Quddus", en: "The Most Holy", ku: "پاک و بێگەرد" },
  { n: 5, ar: "السَّلَامُ", translit: "As-Salam", en: "The Source of Peace", ku: "سەرچاوەی ئاشتی" },
  { n: 6, ar: "الْمُؤْمِنُ", translit: "Al-Mu'min", en: "The Granter of Security", ku: "بەخشەری ئاسایش" },
  { n: 7, ar: "الْمُهَيْمِنُ", translit: "Al-Muhaymin", en: "The Guardian", ku: "چاودێری هەموو شت" },
  { n: 8, ar: "الْعَزِيزُ", translit: "Al-Aziz", en: "The Almighty", ku: "بەهێز و باڵادەست" },
  { n: 9, ar: "الْجَبَّارُ", translit: "Al-Jabbar", en: "The Compeller", ku: "زاڵ و بێنیاز" },
  { n: 10, ar: "الْمُتَكَبِّرُ", translit: "Al-Mutakabbir", en: "The Supreme", ku: "خاوەن گەورەیی" },
  { n: 11, ar: "الْخَالِقُ", translit: "Al-Khaliq", en: "The Creator", ku: "بەدیهێنەر" },
  { n: 12, ar: "الْبَارِئُ", translit: "Al-Bari'", en: "The Originator", ku: "دروستکەری بێ‌نموونە" },
  { n: 13, ar: "الْمُصَوِّرُ", translit: "Al-Musawwir", en: "The Fashioner", ku: "شێوەبەخش" },
  { n: 14, ar: "الْغَفَّارُ", translit: "Al-Ghaffar", en: "The Constant Forgiver", ku: "زۆر لێبووردە" },
  { n: 15, ar: "الْقَهَّارُ", translit: "Al-Qahhar", en: "The All-Subduer", ku: "زاڵکەری هەموو شت" },
  { n: 16, ar: "الْوَهَّابُ", translit: "Al-Wahhab", en: "The Bestower", ku: "زۆر بەخشندە" },
  { n: 17, ar: "الرَّزَّاقُ", translit: "Ar-Razzaq", en: "The Sustainer", ku: "ڕزق‌دەر" },
  { n: 18, ar: "الْفَتَّاحُ", translit: "Al-Fattah", en: "The Opener", ku: "کردنەوەی دەرگا" },
  { n: 19, ar: "الْعَلِيمُ", translit: "Al-Alim", en: "The All-Knowing", ku: "زانا بە هەموو شت" },
  { n: 20, ar: "الْقَابِضُ", translit: "Al-Qabid", en: "The Withholder", ku: "کۆسپدانەر" },
  { n: 21, ar: "الْبَاسِطُ", translit: "Al-Basit", en: "The Extender", ku: "فراوانکەر" },
  { n: 22, ar: "الْخَافِضُ", translit: "Al-Khafid", en: "The Abaser", ku: "نزم‌کەرەوە" },
  { n: 23, ar: "الرَّافِعُ", translit: "Ar-Rafi'", en: "The Exalter", ku: "بەرزکەرەوە" },
  { n: 24, ar: "الْمُعِزُّ", translit: "Al-Mu'izz", en: "The Honourer", ku: "شکۆدەر" },
  { n: 25, ar: "الْمُذِلُّ", translit: "Al-Mudhill", en: "The Dishonourer", ku: "زەلیل‌کەر" },
  { n: 26, ar: "السَّمِيعُ", translit: "As-Sami'", en: "The All-Hearing", ku: "بیسەری هەموو شت" },
  { n: 27, ar: "الْبَصِيرُ", translit: "Al-Basir", en: "The All-Seeing", ku: "بینەری هەموو شت" },
  { n: 28, ar: "الْحَكَمُ", translit: "Al-Hakam", en: "The Judge", ku: "دادوەری بەڕاست" },
  { n: 29, ar: "الْعَدْلُ", translit: "Al-Adl", en: "The Just", ku: "دادپەروەر" },
  { n: 30, ar: "اللَّطِيفُ", translit: "Al-Latif", en: "The Subtle One", ku: "میهرەبانی نازک" },
  { n: 31, ar: "الْخَبِيرُ", translit: "Al-Khabir", en: "The All-Aware", ku: "ئاگا لە هەموو شت" },
  { n: 32, ar: "الْحَلِيمُ", translit: "Al-Halim", en: "The Forbearing", ku: "دەست‌بەرد و خۆڕاگر" },
  { n: 33, ar: "الْعَظِيمُ", translit: "Al-Azim", en: "The Magnificent", ku: "گەورە و مەزن" },
  { n: 34, ar: "الْغَفُورُ", translit: "Al-Ghafur", en: "The All-Forgiving", ku: "زۆر لێخۆشبوو" },
  { n: 35, ar: "الشَّكُورُ", translit: "Ash-Shakur", en: "The Appreciative", ku: "سوپاسگوزار" },
  { n: 36, ar: "الْعَلِيُّ", translit: "Al-Ali", en: "The Most High", ku: "بەرز و پایەبەرز" },
  { n: 37, ar: "الْكَبِيرُ", translit: "Al-Kabir", en: "The Most Great", ku: "زۆر گەورە" },
  { n: 38, ar: "الْحَفِيظُ", translit: "Al-Hafiz", en: "The Preserver", ku: "پاراستنکەر" },
  { n: 39, ar: "الْمُقِيتُ", translit: "Al-Muqit", en: "The Nourisher", ku: "خۆراک‌بەخش" },
  { n: 40, ar: "الْحَسِيبُ", translit: "Al-Hasib", en: "The Reckoner", ku: "لێپرسینەوەکەر" },
  { n: 41, ar: "الْجَلِيلُ", translit: "Al-Jalil", en: "The Majestic", ku: "خاوەن جەلال" },
  { n: 42, ar: "الْكَرِيمُ", translit: "Al-Karim", en: "The Generous", ku: "بەخشندە و پیرۆز" },
  { n: 43, ar: "الرَّقِيبُ", translit: "Ar-Raqib", en: "The Watchful", ku: "چاودێر" },
  { n: 44, ar: "الْمُجِيبُ", translit: "Al-Mujib", en: "The Responsive", ku: "وەڵامدەرەوە" },
  { n: 45, ar: "الْوَاسِعُ", translit: "Al-Wasi'", en: "The All-Encompassing", ku: "فراوان" },
  { n: 46, ar: "الْحَكِيمُ", translit: "Al-Hakim", en: "The Most Wise", ku: "دانا" },
  { n: 47, ar: "الْوَدُودُ", translit: "Al-Wadud", en: "The Most Loving", ku: "زۆر خۆشەویست" },
  { n: 48, ar: "الْمَجِيدُ", translit: "Al-Majid", en: "The Most Glorious", ku: "پایە بەرز" },
  { n: 49, ar: "الْبَاعِثُ", translit: "Al-Ba'ith", en: "The Resurrector", ku: "زیندووکەرەوە" },
  { n: 50, ar: "الشَّهِيدُ", translit: "Ash-Shahid", en: "The Witness", ku: "شایەتی هەموو شت" },
  { n: 51, ar: "الْحَقُّ", translit: "Al-Haqq", en: "The Truth", ku: "ڕاستی" },
  { n: 52, ar: "الْوَكِيلُ", translit: "Al-Wakil", en: "The Trustee", ku: "کارگوزار" },
  { n: 53, ar: "الْقَوِيُّ", translit: "Al-Qawi", en: "The Most Strong", ku: "زۆر بەهێز" },
  { n: 54, ar: "الْمَتِينُ", translit: "Al-Matin", en: "The Firm", ku: "پتەو" },
  { n: 55, ar: "الْوَلِيُّ", translit: "Al-Wali", en: "The Protecting Friend", ku: "پارێزەری دۆست" },
  { n: 56, ar: "الْحَمِيدُ", translit: "Al-Hamid", en: "The All-Praiseworthy", ku: "شایانی سوپاس" },
  { n: 57, ar: "الْمُحْصِي", translit: "Al-Muhsi", en: "The Accounter", ku: "ژماردنکەر" },
  { n: 58, ar: "الْمُبْدِئُ", translit: "Al-Mubdi'", en: "The Originator", ku: "دەست‌پێکەر" },
  { n: 59, ar: "الْمُعِيدُ", translit: "Al-Mu'id", en: "The Restorer", ku: "گەڕاندنەوە" },
  { n: 60, ar: "الْمُحْيِي", translit: "Al-Muhyi", en: "The Giver of Life", ku: "ژیان‌بەخش" },
  { n: 61, ar: "الْمُمِيتُ", translit: "Al-Mumit", en: "The Bringer of Death", ku: "مردن‌بەخش" },
  { n: 62, ar: "الْحَيُّ", translit: "Al-Hayy", en: "The Ever-Living", ku: "زیندووی هەمیشەیی" },
  { n: 63, ar: "الْقَيُّومُ", translit: "Al-Qayyum", en: "The Sustainer", ku: "ڕاگری هەموو شت" },
  { n: 64, ar: "الْوَاجِدُ", translit: "Al-Wajid", en: "The Perceiver", ku: "دۆزەرەوە" },
  { n: 65, ar: "الْمَاجِدُ", translit: "Al-Majid", en: "The Illustrious", ku: "شکۆدار" },
  { n: 66, ar: "الْوَاحِدُ", translit: "Al-Wahid", en: "The One", ku: "یەکێک" },
  { n: 67, ar: "الْأَحَدُ", translit: "Al-Ahad", en: "The Only One", ku: "تەنیا یەک" },
  { n: 68, ar: "الصَّمَدُ", translit: "As-Samad", en: "The Eternal", ku: "بێ‌پێویست" },
  { n: 69, ar: "الْقَادِرُ", translit: "Al-Qadir", en: "The Capable", ku: "توانادار" },
  { n: 70, ar: "الْمُقْتَدِرُ", translit: "Al-Muqtadir", en: "The Powerful", ku: "بەتوانا" },
  { n: 71, ar: "الْمُقَدِّمُ", translit: "Al-Muqaddim", en: "The Expediter", ku: "پێش‌خەر" },
  { n: 72, ar: "الْمُؤَخِّرُ", translit: "Al-Mu'akhkhir", en: "The Delayer", ku: "دواخەر" },
  { n: 73, ar: "الْأَوَّلُ", translit: "Al-Awwal", en: "The First", ku: "یەکەم" },
  { n: 74, ar: "الْآخِرُ", translit: "Al-Akhir", en: "The Last", ku: "کۆتایی" },
  { n: 75, ar: "الظَّاهِرُ", translit: "Az-Zahir", en: "The Manifest", ku: "دیار" },
  { n: 76, ar: "الْبَاطِنُ", translit: "Al-Batin", en: "The Hidden", ku: "شاراوە" },
  { n: 77, ar: "الْوَالِي", translit: "Al-Wali", en: "The Governor", ku: "فەرمانڕەوا" },
  { n: 78, ar: "الْمُتَعَالِي", translit: "Al-Muta'ali", en: "The Most Exalted", ku: "بەرزی مەزن" },
  { n: 79, ar: "الْبَرُّ", translit: "Al-Barr", en: "The Source of Goodness", ku: "بەخێری زۆر" },
  { n: 80, ar: "التَّوَّابُ", translit: "At-Tawwab", en: "The Accepter of Repentance", ku: "قبوڵکەری تەوبە" },
  { n: 81, ar: "الْمُنْتَقِمُ", translit: "Al-Muntaqim", en: "The Avenger", ku: "تۆڵەسێن" },
  { n: 82, ar: "الْعَفُوُّ", translit: "Al-Afuw", en: "The Pardoner", ku: "لێخۆشبوو" },
  { n: 83, ar: "الرَّءُوفُ", translit: "Ar-Ra'uf", en: "The Most Kind", ku: "زۆر میهرەبان" },
  { n: 84, ar: "مَالِكُ الْمُلْكِ", translit: "Malik al-Mulk", en: "Owner of All", ku: "خاوەنی موڵک" },
  { n: 85, ar: "ذُو الْجَلَالِ وَالْإِكْرَامِ", translit: "Dhul-Jalali wal-Ikram", en: "Lord of Majesty & Bounty", ku: "خاوەن جەلال و ڕێز" },
  { n: 86, ar: "الْمُقْسِطُ", translit: "Al-Muqsit", en: "The Equitable", ku: "دادپەروەر" },
  { n: 87, ar: "الْجَامِعُ", translit: "Al-Jami'", en: "The Gatherer", ku: "کۆکەرەوە" },
  { n: 88, ar: "الْغَنِيُّ", translit: "Al-Ghani", en: "The Self-Sufficient", ku: "بێ‌نیاز" },
  { n: 89, ar: "الْمُغْنِي", translit: "Al-Mughni", en: "The Enricher", ku: "دەوڵەمەندکەر" },
  { n: 90, ar: "الْمَانِعُ", translit: "Al-Mani'", en: "The Preventer", ku: "ڕێگری" },
  { n: 91, ar: "الضَّارُّ", translit: "Ad-Darr", en: "The Distresser", ku: "زیانبەخشی حیکمەت" },
  { n: 92, ar: "النَّافِعُ", translit: "An-Nafi'", en: "The Benefactor", ku: "سوودبەخش" },
  { n: 93, ar: "النُّورُ", translit: "An-Nur", en: "The Light", ku: "ڕووناکی" },
  { n: 94, ar: "الْهَادِي", translit: "Al-Hadi", en: "The Guide", ku: "ڕێنمای" },
  { n: 95, ar: "الْبَدِيعُ", translit: "Al-Badi'", en: "The Incomparable", ku: "بێ‌وێنە" },
  { n: 96, ar: "الْبَاقِي", translit: "Al-Baqi", en: "The Everlasting", ku: "هەمیشەیی" },
  { n: 97, ar: "الْوَارِثُ", translit: "Al-Warith", en: "The Inheritor", ku: "میراتخۆر" },
  { n: 98, ar: "الرَّشِيدُ", translit: "Ar-Rashid", en: "The Guide to the Right Path", ku: "ڕێنمای بۆ ڕاستی" },
  { n: 99, ar: "الصَّبُورُ", translit: "As-Sabur", en: "The Patient", ku: "زۆر خۆڕاگر" },
];
